// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"database/sql"
	"plataforma-cursos/internal/controllers"
	"plataforma-cursos/internal/services"
	"plataforma-cursos/pkg/database"
)

// Injectors from wire.go:

func InitializeCourseController() *controllers.CourseController {
	db := ProvideDB()
	courseService := services.NewCourseService(db)
	courseController := controllers.NewCourseController(courseService)
	return courseController
}

func InitializeUserController() *controllers.UserController {
	db := ProvideDB()
	userService := services.NewUserService(db)
	userController := controllers.NewUserController(userService)
	return userController
}

// wire.go:

func ProvideDB() *sql.DB {
	return database.GetDB()
}
